%YAML 1.2
---
# Snapcraft Recipe for Hunspell Dictionaries
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * Snapcraft.yaml reference
#   https://forum.snapcraft.io/t/snapcraft-yaml-reference/4276
# * The snapcraft syntax
#   https://docs.snapcraft.io/build-snaps/syntax
# * Snap Docs
#   https://snapdocs.labix.org
# * Latest doc topics in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft

name: hunspell-dictionaries
summary: Dictionaries for the most popular spellchecking library
description: |
  This is a content-shared snap for snaps that depend on the Hunspell spellchecking dictionaries.

  Refer "The content interface - doc - snapcraft.io" topic for information of using this snap:
  https://forum.snapcraft.io/t/the-content-interface/1074/1

version: determined-by-version-script
version-script: ./snap/utilities/set-snap-version.bash

confinement: devmode # use 'strict' once you have the right plugs and slots
grade: devel
icon: snap/gui/icon.png

slots:
  hunspell-dictionaries:
    interface: content
    read:
    - $SNAP/usr/share/hunspell
    - $SNAP/usr/share/myspell

  hunspell-launchers:
    interface: content
    read:
    - $SNAP/bin

parts:
  # Assets from the snap packaging, refer each READMEs under the `snap` folder for more information
  assets:
    source: snap
    source-type: local
    plugin: nil

    override-build: |
      set \
        -o errexit \
        -o nounset

      ./utilities/install-assets.bash
    prime:
    - -utilities
    - -patches

  spellcheck-dictionaries:
    plugin: nil
    # Poedit sources will be used when `source` is ommitted, avoid this
    # behavior
    override-pull: 'true'
    override-build: |
      set -eu

      # Download all dictionary packages, and extract to install prefix
      apt download $(
        apt-cache search '^hunspell-.*$' \
          | sort \
          | grep \
            --extended-regexp \
            --invert-match \
            '(myspell|dbgsym|tools|transitional|dependency)' \
          | cut --fields=1 --delimiter=' ' \
          | tr '\n' ' '
      )
      find -name '*.deb' \
        | xargs \
          --max-args=1 \
          --replace={} \
          --verbose \
          dpkg-deb --extract {} ../install

    filesets:
      hunspell-dictionaries:
      - usr/share/hunspell
      myspell-dictionaries:
      - usr/share/myspell
    stage:
    - $hunspell-dictionaries
    #- $myspell-dictionaries
    prime:
    - $hunspell-dictionaries
    #- $myspell-dictionaries
