%YAML 1.1
---
# Snapcraft Recipe for Hunspell Dictionaries
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * Snapcraft.yaml reference
#   https://forum.snapcraft.io/t/snapcraft-yaml-reference/4276
# * The snapcraft syntax
#   https://docs.snapcraft.io/build-snaps/syntax
# * Snap Docs
#   https://snapdocs.labix.org
# * Latest doc topics in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft

name: hunspell-dictionaries-1-3-1604
summary: Dictionaries for the most popular spellchecking library
description: |
  This is a content-shared snap for snaps that depend on the Hunspell spellchecking dictionaries.

  This snap does not provide any applications and is not meant for regular users.

  Refer "The content interface - doc - snapcraft.io" topic for information of using this snap:
  https://forum.snapcraft.io/t/the-content-interface/1074/1

adopt-info: hunspell-dictionaries
confinement: strict
grade: stable
icon: snap/gui/icon.png
base: core
architectures:
  - build-on: i386
    run-on: all

slots:
  # NOTE:
  #   Versioning scheme: Hunspell library major+minor version from Ubuntu archive +  Ubuntu software archive release version
  #   Not all dictionaries come from libreoffice-dictionaries, just most of them, thus not using its version
  #   We assume all dictionaries shipped in this Ubuntu release are compatible with the accompanied Hunspell library
  hunspell-dictionaries-1-3-1604:
    content: hunspell-dictionaries-1-3-1604
    interface: content
    read:
      - $SNAP/usr/share/hunspell

parts:
  scriptlets:
    source: snap/local/scriptlets
    plugin: dump
    organize:
      '*': scriptlets/
    prime:
      - -*

  hunspell-dictionaries:
    build-packages:
      # for the set-snap-version scriptlet
      - try:
        - git
      - else:
        - git-core
      - lsb-release

    after:
      - scriptlets
    override-pull: |
      set -eu

      "${SNAPCRAFT_STAGE}"/scriptlets/set-snap-version.bash

    plugin: nil
    override-build: |
      set -eu

      # Download all dictionary packages, and extract to install prefix
      apt download $(
        apt-cache search '^hunspell-.*$' \
          | sort \
          | grep \
            --extended-regexp \
            --invert-match \
            '(myspell|dbgsym|tools|transitional|dependency)' \
          | cut --fields=1 --delimiter=' ' \
          | tr '\n' ' '
      )
      find -name '*.deb' \
        | xargs \
          --max-args=1 \
          --replace={} \
          --verbose \
          dpkg-deb --extract {} "${SNAPCRAFT_PART_INSTALL}"

    filesets:
      copyright:
      - usr/share/doc/*/copyright
      hunspell-dictionaries:
      - usr/share/hunspell
    stage:
      - $copyright
      - $hunspell-dictionaries
    prime:
      - $copyright
      - $hunspell-dictionaries
